/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-vika-turquoise/20',
    'bg-vika-teal/20',
    'bg-vika-violet/20',
    'bg-vika-coral/20',
    'bg-vika-yellow/20',
    'bg-vika-amber/20',
    'bg-vika-sky/20',
    'bg-vika-teal',
    'bg-vika-amber',
    'bg-vika-sky',
    'border-vika-turquoise',
    'border-vika-teal',
    'border-vika-violet',
    'border-vika-coral',
    'border-vika-yellow',
    'border-vika-amber',
    'border-vika-sky',
    'text-vika-turquoise',
    'text-vika-teal',
    'text-vika-violet',
    'text-vika-coral',
    'text-vika-yellow',
    'text-vika-amber',
    'text-vika-sky',
  ],
  theme: {
    extend: {
      colors: {
        vika: {
          turquoise: '#3DD6D0',
          teal: '#1BAB9B',
          violet: '#6677F5',
          coral: '#F7A9A8',
          yellow: '#D4D017',
          amber: '#F59E0B',
          sky: '#0EA5E9',
        },
      },
    },
  },
  plugins: [],
}
